- arguments:
    [
      -XApplicativeDo,
      -XBangPatterns,
      -XConstraintKinds,
      -XDataKinds,
      -XDefaultSignatures,
      -XDeriveFoldable,
      -XDeriveFunctor,
      -XDeriveGeneric,
      -XDeriveLift,
      -XDeriveTraversable,
      -XEmptyCase,
      -XEmptyDataDecls,
      -XExistentialQuantification,
      -XFlexibleContexts,
      -XFlexibleInstances,
      -XFunctionalDependencies,
      -XGADTs,
      -XGeneralizedNewtypeDeriving,
      -XInstanceSigs,
      -XKindSignatures,
      -XLambdaCase,
      -XMultiParamTypeClasses,
      -XMultiWayIf,
      -XNamedFieldPuns,
      -XOverloadedStrings,
      -XPatternSynonyms,
      -XRankNTypes,
      -XScopedTypeVariables,
      -XStandaloneDeriving,
      -XTupleSections,
      -XTypeApplications,
      -XTypeFamilies,
      -XTypeFamilyDependencies,
      -XTypeOperators,
    ]
