name: miso-spa
version: 0.1.0.0
github: "tehnix/playground-spa-miso"
license: BSD3
author: "Tehnix"
maintainer: "ckl@codetalk.io"
copyright: "2020 Tehnix"
description: "Please see the README on GitHub at <https://github.com/githubuser/app#readme>"
extra-source-files:
  - README.md
  - Changelog.md

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wincomplete-patterns
  - -Wpartial-fields
  - -fhide-source-paths
  - -Wno-type-defaults

default-extensions:
  # Working with records.
  - DuplicateRecordFields
  - OverloadedLabels
  # Working with Generics.
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - NoMonomorphismRestriction
  # Other useful extensions.
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  - base-noprelude
  - relude
  - miso >= 1.5.0.0
  - lens
  - generic-lens
  - bytestring
  - aeson
  - network-uri
  - servant

library:
  source-dirs: src

executables:
  app-exe:
    main: Main.hs
    source-dirs: app
    when:
      - condition: impl(ghcjs)
        then:
          dependencies:
            - miso-spa
        else:
          dependencies:
            - miso-spa
            - jsaddle
            - jsaddle-warp
            - transformers
            - warp
            - websockets
            - servant

tests:
  app-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - miso-spa

  doctests:
    main: Doctests.hs
    ghc-options:
      - -threaded
    dependencies:
      - miso-spa
      - doctest >= 0.16.3
