name: miso-spa
version: 0.1.0.0
github: "tehnix/playground-spa-miso"
license: BSD3
author: "Tehnix"
maintainer: "ckl@codetalk.io"
copyright: "2020 Tehnix"
description: "Please see the README on GitHub at <https://github.com/githubuser/app#readme>"
extra-source-files:
  - README.md
  - Changelog.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  - base
  - lens
  - miso
  - network-uri
  - servant

library:
  source-dirs: src

executables:
  app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      - condition: impl(ghcjs)
        then:
          dependencies:
            - miso-spa
        else:
          dependencies:
            - miso-spa
            - jsaddle
            - jsaddle-warp
            - transformers
            - warp
            - websockets
            - servant

tests:
  app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - miso-spa
