name: miso-spa
version: 0.1.0.0
github: "tehnix/playground-spa-miso"
license: BSD3
author: "Tehnix"
maintainer: "ckl@codetalk.io"
copyright: "2020 Tehnix"
description: "Please see the README on GitHub at <https://github.com/githubuser/app#readme>"
build-type: Custom
extra-source-files:
  - README.md
  - Changelog.md

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wincomplete-patterns
  - -Wpartial-fields
  - -fhide-source-paths
  - -Wno-type-defaults
  # We the preprocessor instead of `-fplugin=RecordDotPreprocessor` to get ghcide support
  # (see https://github.com/digital-asset/ghcide/issues/279).
  - -F -pgmF=record-dot-preprocessor

default-extensions:
  # Working with records.
  - DuplicateRecordFields
  # Working with Generics.
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - NoMonomorphismRestriction
  # Other useful extensions.
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  # Set up Relude.
  - base-noprelude
  - relude
  # Miso and related libraries (e.g. routing).
  - miso >= 1.5.0.0
  - servant
  - network-uri
  # Working with records.
  # - record-dot-preprocessor # Needs GHC package, which is not available for GHCJS.
  - record-hasfield
  - lens
  - generic-lens
  # Other dependencies.
  - bytestring
  - aeson

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >= 1.0.8 && <1.1

library:
  source-dirs: src

executables:
  app-exe:
    main: Main.hs
    source-dirs: app
    when:
      - condition: impl(ghcjs)
        then:
          dependencies:
            - miso-spa
        else:
          dependencies:
            - miso-spa
            - jsaddle
            - jsaddle-warp
            - transformers
            - warp
            - websockets
            - servant

tests:
  app-test: # This name is kept in sync with Setup.hs
    main: Main.hs
    source-dirs: test
    dependencies:
      - miso-spa
      - hspec
      - hspec-discover
      - doctest >= 0.16.3
  # doctests:
  #   main: doctests.hs
  #   ghc-options:
  #     - -threaded
  #   dependencies:
  #     - miso-spa
  #     - doctest >= 0.16.3
