name: cd

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on: [push]

jobs:
  ghcjs-build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: hercules-ci miso-haskell # Add general and Miso's cachix

      - name: Build GHCJS version
        run: nix-shell shell-ghcjs.nix --run build

      - name: Optimize build
        run: nix-shell shell-ghcjs.nix --run optimize

  ghc-build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: hercules-ci miso-haskell # Add general and Miso's cachix

      - name: Build GHC version
        run: nix-shell --run build
# Enable cache for cabal
# - uses: actions/cache@v1
#   name: Cache .stack-work
#   with:
#     path: .stack-work
#     key: ${{ runner.os }}-${{env.GHC_VERSION}}-stack-work
# - uses: actions/cache@v1
#   name: Cache ~/.cabal/store
#   with:
#     path: ~/.cabal/store
#     key: ${{ runner.os }}-${{env.GHC_VERSION}}-cabal-store
# - uses: actions/cache@v1
#   name: Cache stack
#   with:
#     path: ~/.stack
#     key: ${{ runner.os }}-${{env.GHC_VERSION}}-stack
