name: ci

# Check out https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on: [push]

jobs:
  # Run our release build with optimizations.
  ghcjs:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: hercules-ci # Add general cachix
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: miso-haskell # Add Miso's cachix

      - name: Bootstrap nix environment
        run: nix-shell shell-ghcjs.nix --max-jobs auto --run 'echo "Ready"'

      - name: Update hackage packages # If things don't work, change to cabal v2-update 'hackage.haskell.org,2020-04-10T21:50:21Z'
        run: nix-shell shell-ghcjs.nix --run 'cabal --project-file=ghcjs.project v2-update'

      - name: Build GHCJS Version
        run: nix-shell shell-ghcjs.nix --run build # or: nix-build -A release

      - name: Optimize Build
        run: nix-shell shell-ghcjs.nix --run optimize

  # Run our development build along with doc and unit tests.
  ghc:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: hercules-ci # Add general cachix
      - uses: cachix/cachix-action@v5
        with:
          skipNixBuild: true
          name: miso-haskell # Add Miso's cachix

      - name: Bootstrap nix environment
        run: nix-shell --max-jobs auto --run 'echo "Ready"'

      - name: Update hackage packages # If things don't work, change to cabal v2-update 'hackage.haskell.org,2020-04-10T21:50:21Z'
        run: nix-shell --run 'cabal v2-update'

      - name: Build GHC Version
        run: nix-shell --run 'cabal v2-build --enable-tests'

      - name: Test Application
        run: nix-shell --run 'cabal v2-test test:app-test'
